development:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
    google_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
    google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>

    facebook_client_id: <%= ENV["FACEBOOK_CLIENT_ID"] %>
    facebook_client_secret: <%= ENV["FACEBOOK_CLIENT_SECRET"] %>

test:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
    secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>